apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api-app
  namespace: default
spec:
  chart:
    spec:
      chart: ./flux-agro-cd-lab         
  values:
    image:
      repository: radeczu/apitestapp
      tag: "1.0.1"