apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api-app
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: flux-agro-cd-lab
      sourceRef:
        kind: GitRepository
        name: flux-agro-cd-lab
        namespace: flux-system
  values:
    image:
      repository: radeczu/apitestapp
      tag: "1.0.1"