apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: api-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: "./flux-agro-cd-lab/clusters/minikube"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-agro-cd-lab
    namespace: flux-system
  targetNamespace: default
  validation: client
  # resources:
  #   - helmrelease-api-app.yaml